# Generated by Django 3.2 on 2021-05-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210513_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='like',
            new_name='likes',
        ),
    ]
